const KEY='bird_planner_clients_v5_verified';
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const FULL_MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const SECTIONS={
 schedule:{sub:'Schedule / Calendar + Agenda',tabs:[['calendar','Calendar + Agenda','Calendar view, agenda, and tasks'],['newJob','New Job Entry','Add scheduled or completed jobs'],['newEvent','New Event Entry','Add personal events']]},
 clients:{sub:'Clients / Directory',tabs:[['directory','Directory','Alphabetical client list.'],['client','Client','Selected client record and totals.'],['invoices','Invoices','All client invoices in numerical order.']]},
 supplies:{sub:'Supplies / Supply List',tabs:[['list','Supply List','All supplies. Selecting item opens item page.'],['item','Item','Specific supply item details.'],['inventory','Inventory','All supply quantities remaining.'],['receipts','Receipts','Receipts for supply purchases.']]},
 banking:{sub:'Banking / Accounts',tabs:[['accounts','Accounts','Main spending and savings accounts.'],['trackers','Trackers','Money received, spent, saved, and categories.'],['receipts','Receipts','All banking receipts.']]}
};
const now=new Date();
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{section:'schedule',tabs:{schedule:'calendar',clients:'directory',supplies:'list',banking:'accounts'},notes:{},year:now.getFullYear(),month:now.getMonth(),selectedDate:dateKey(now),calendarData:{},clients:{},selectedClient:''};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dateKey(d){let x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}
function makeKey(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function parseKey(k){let [y,m,d]=k.split('-').map(Number);return {y,m:m-1,d}}
function ensureDay(k){if(!state.calendarData[k])state.calendarData[k]={agenda:[],tasks:[],notes:''};if(!state.calendarData[k].agenda)state.calendarData[k].agenda=[];if(!state.calendarData[k].tasks)state.calendarData[k].tasks=[];if(state.calendarData[k].notes===undefined)state.calendarData[k].notes='';return state.calendarData[k]}
function setSection(s){state.section=s;save();render()}
function setTab(t){state.tabs[state.section]=t;save();render()}
function render(){document.querySelectorAll('.sideTab').forEach(b=>b.classList.toggle('active',b.dataset.section===state.section));subtitle.textContent=SECTIONS[state.section].sub;subtabs.innerHTML=SECTIONS[state.section].tabs.map(t=>`<button class="subtab ${state.tabs[state.section]===t[0]?'active':''}" onclick="setTab('${t[0]}')">${t[1]}</button>`).join('');let tab=SECTIONS[state.section].tabs.find(t=>t[0]===state.tabs[state.section]);if(state.section==='schedule'&&tab[0]==='calendar'){content.innerHTML=renderScheduleCalendar();return}if(state.section==='schedule'&&tab[0]==='newJob'){content.innerHTML=renderJobForm();return}if(state.section==='schedule'&&tab[0]==='newEvent'){content.innerHTML=renderEventForm();return}if(state.section==='clients'&&tab[0]==='directory'){content.innerHTML=renderClientDirectory();return}if(state.section==='clients'&&tab[0]==='client'){content.innerHTML=renderClientRecord();return}if(state.section==='clients'&&tab[0]==='invoices'){content.innerHTML=renderClientInvoices();return}content.innerHTML=pageTemplate(state.section,tab)}
function pageTemplate(section,tab){return `<div class="titleRow"><div><h2>${tab[1]}</h2><p>${tab[2]}</p></div><div class="note">Blank Page Template</div></div><div class="box"><p>This page is ready to build next.</p></div>`}
function renderScheduleCalendar(){let y=state.year||now.getFullYear(),m=state.month??now.getMonth();state.year=y;state.month=m;let first=new Date(y,m,1).getDay(),total=new Date(y,m+1,0).getDate(),todayKey=dateKey(new Date());let monthTabs=MONTHS.map((name,i)=>`<button class="monthBtn ${i===m?'active':''}" onclick="setCalendarMonth(${i})">${name}</button>`).join('');let days=['SUN','MON','TUE','WED','THU','FRI','SAT'].map(d=>`<div>${d}</div>`).join('');let grid='';for(let i=0;i<first;i++)grid+=`<div class="calDay blank"></div>`;for(let d=1;d<=total;d++){let k=makeKey(y,m,d),data=ensureDay(k),agenda=data.agenda||[];let previews=agenda.slice(0,3).map(item=>`<div class="preview ${item.canceled?'canceled':''}">${formatTime(item.time)}: ${escapeHtml(item.title||'')}</div>`).join('');if(agenda.length>3)previews+=`<div class="preview">+${agenda.length-3} more</div>`;grid+=`<div class="calDay ${k===state.selectedDate?'selected':''} ${k===todayKey?'today':''}" onclick="selectCalendarDay('${k}')"><div class="dayNum">${d}</div>${previews}</div>`}let selectedData=ensureDay(state.selectedDate),selectedDateObj=new Date(state.selectedDate+'T12:00:00');return `<div class="monthTabs">${monthTabs}</div><div class="calendarTitle"><button onclick="changeCalendarYear(-1)">‹ ${y-1}</button><h2>${FULL_MONTHS[m]} ${y}</h2><button onclick="changeCalendarYear(1)">${y+1} ›</button></div><div class="weekdays">${days}</div><div class="calendarGrid">${grid}</div><div class="dayBottom"><div class="dailyBox"><h3>${selectedDateObj.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric',year:'numeric'})}</h3><h4>Agenda</h4><div>${selectedData.agenda.map((item,idx)=>`<div class="agendaRow ${item.canceled?'canceled':''}"><span>${formatTime(item.time)}: ${escapeHtml(item.title||'')}</span><button class="smallBtn" onclick="toggleCancel(${idx})">×</button></div>`).join('')||'<p class="note">No agenda items yet.</p>'}</div><div class="addRow"><input id="newAgendaTime" placeholder="8a"><input id="newAgendaTitle" placeholder="Weed Eating"><button onclick="addAgenda()">Add</button></div></div><div class="dailyBox"><h4>Tasks</h4><div>${selectedData.tasks.map((task,idx)=>`<div class="taskRow ${task.done?'done':''}"><input type="checkbox" ${task.done?'checked':''} onchange="updateTask(${idx},'done',this.checked)"><input type="text" value="${escapeHtml(task.text||'')}" oninput="updateTask(${idx},'text',this.value)"><button class="smallBtn" onclick="deleteTask(${idx})">×</button></div>`).join('')||'<p class="note">No tasks yet.</p>'}</div><div class="addTaskRow"><input id="newTaskText" placeholder="Add task"><button onclick="addTask()">Add</button></div><h4>Notes</h4><textarea class="notesArea" oninput="updateNotes(this.value)" placeholder="Daily notes...">${escapeHtml(selectedData.notes||'')}</textarea></div></div>`}
function renderJobForm(){let names=Object.keys(state.clients||{}).sort();return `<div class="titleRow"><div><h2>New Job Entry</h2><p>Saves to calendar and auto-creates/updates client file.</p></div><div class="note">Schedule / Job</div></div><div class="box"><datalist id="clientNames">${names.map(n=>`<option value="${escapeHtml(n)}"></option>`).join('')}</datalist><label>Date</label><input id="jobDate" type="date" value="${state.selectedDate}"><label>Job Status</label><select id="jobStatus"><option value="scheduled">Scheduled Job</option><option value="completed">Completed Job</option></select><label>Title</label><input id="jobTitle" placeholder="Weed Eating"><div class="two"><div><label>Time In</label><input id="jobStart" placeholder="8a" oninput="calcJobPay()"></div><div><label>Time Out</label><input id="jobEnd" placeholder="4p" oninput="calcJobPay()"></div></div><label>Total Hours</label><input id="jobHours" type="number" step="0.25" oninput="calcJobPay()"><div class="two"><div><label>Pay Type</label><select id="jobPayType" onchange="calcJobPay()"><option value="hourly">Hourly</option><option value="flat">Flat Rate</option></select></div><div><label>Rate / Flat Amount</label><input id="jobRate" type="number" step="0.01" oninput="calcJobPay()"></div></div><label>Total Price</label><input id="jobOwed" type="number" step="0.01" readonly><label>Amount Received</label><input id="jobReceived" type="number" step="0.01"><label>Client Name</label><input id="jobClient" list="clientNames" placeholder="Client name" oninput="autoFillClient()"><label>Phone</label><input id="jobPhone" placeholder="Phone"><label>Address</label><input id="jobAddress" placeholder="Address"><label>Notes</label><textarea id="jobNotes" placeholder="Job notes..."></textarea><div class="actions"><button class="save" onclick="saveJob()">Save Job</button><button onclick="setTab('calendar')">Back</button></div></div>`}
function renderEventForm(){return `<div class="titleRow"><div><h2>New Event Entry</h2><p>Add personal events. Events show on the calendar but do not count as jobs.</p></div><div class="note">Schedule / Event</div></div><div class="box"><label>Date</label><input id="eventDate" type="date" value="${state.selectedDate}"><label>Title</label><input id="eventTitle" placeholder="Appointment"><label>Time</label><input id="eventTime" placeholder="2p"><label>Location</label><input id="eventLocation" placeholder="Location"><label>Notes</label><textarea id="eventNotes" placeholder="Event notes..."></textarea><div class="actions"><button class="save" onclick="saveEvent()">Save Event</button><button onclick="setTab('calendar')">Back</button></div></div>`}
function renderClientDirectory(){syncClientsFromJobs();let names=Object.keys(state.clients||{}).sort((a,b)=>a.localeCompare(b));return `<div class="titleRow"><div><h2>Client Directory</h2><p>Alphabetical list. Tap a client to open their file.</p></div><div class="note">${names.length} clients</div></div><div class="clientList">${names.map(n=>{let t=clientTotals(n);return `<div class="clientCard" onclick="openClient('${escapeAttr(n)}')"><b>${escapeHtml(n)}</b><small>${escapeHtml(state.clients[n].phone||'')} ${escapeHtml(state.clients[n].address||'')}</small><br><small>${t.hours.toFixed(2)} hrs • Paid ${money(t.paid)} • Owed ${money(t.balance)}</small></div>`}).join('')||'<p class="note">No clients yet. Save a job with a client name to auto-create one.</p>'}</div>`}
function renderClientRecord(){syncClientsFromJobs();let n=state.selectedClient||Object.keys(state.clients||{}).sort()[0]||'';state.selectedClient=n;if(!n)return `<div class="titleRow"><div><h2>Client Record</h2><p>No client selected yet.</p></div></div>`;let c=state.clients[n]||{},t=clientTotals(n),jobs=jobsForClient(n);return `<div class="titleRow"><div><h2>${escapeHtml(n)}</h2><p>Client file auto-syncs from job entries.</p></div><button onclick="setTab('directory')">Directory</button></div><div class="trackers"><div class="tracker">Hours<b>${t.hours.toFixed(2)}</b></div><div class="tracker">Charged<b>${money(t.charged)}</b></div><div class="tracker">Paid<b>${money(t.paid)}</b></div><div class="tracker">Balance<b>${money(t.balance)}</b></div></div><div class="box"><label>Name</label><input id="clientNameEdit" value="${escapeHtml(n)}"><label>Phone</label><input id="clientPhoneEdit" value="${escapeHtml(c.phone||'')}"><label>Address</label><input id="clientAddressEdit" value="${escapeHtml(c.address||'')}"><label>Notes</label><textarea id="clientNotesEdit">${escapeHtml(c.notes||'')}</textarea><div class="actions"><button class="save" onclick="saveClientEdit()">Save Client</button></div></div><h3>Job History</h3><div class="clientList">${jobs.map(j=>`<div class="historyCard"><b>${escapeHtml(j.date)} — ${formatTime(j.time)}: ${escapeHtml(j.title)}</b><small>${j.status||''} • ${Number(j.hours||0).toFixed(2)} hrs • Charged ${money(j.owed)} • Paid ${money(j.received)}</small></div>`).join('')||'<p class="note">No jobs for this client yet.</p>'}</div>`}
function renderClientInvoices(){return `<div class="titleRow"><div><h2>Invoices</h2><p>Invoice system comes next.</p></div></div><div class="box"><p>Next we will build invoice numbers, paid/unpaid cards, signatures, and client-linked invoices here.</p></div>`}
function setCalendarMonth(m){state.month=m;state.selectedDate=makeKey(state.year,m,1);save();render()}
function changeCalendarYear(n){state.year+=n;state.selectedDate=makeKey(state.year,state.month,1);save();render()}
function selectCalendarDay(k){state.selectedDate=k;let p=parseKey(k);state.year=p.y;state.month=p.m;save();render()}
function addAgenda(){let time=document.getElementById('newAgendaTime').value.trim(),title=document.getElementById('newAgendaTitle').value.trim();if(!time||!title)return;let d=ensureDay(state.selectedDate);d.agenda.push({time,title,type:'quick',canceled:false});sortAgenda(d.agenda);save();render()}
function saveJob(){let date=document.getElementById('jobDate').value,title=document.getElementById('jobTitle').value,time=document.getElementById('jobStart').value;if(!date||!title)return;calcJobPay();let client=document.getElementById('jobClient').value.trim();let d=ensureDay(date);let job={time,title,type:'job',status:document.getElementById('jobStatus').value,end:document.getElementById('jobEnd').value,payType:document.getElementById('jobPayType').value,rate:document.getElementById('jobRate').value,client,phone:document.getElementById('jobPhone').value,address:document.getElementById('jobAddress').value,hours:document.getElementById('jobHours').value,owed:document.getElementById('jobOwed').value,received:document.getElementById('jobReceived').value,notes:document.getElementById('jobNotes').value,canceled:false};d.agenda.push(job);if(client)upsertClientFromJob(job);sortAgenda(d.agenda);state.selectedDate=date;let p=parseKey(date);state.year=p.y;state.month=p.m;save();setTab('calendar')}
function saveEvent(){let date=document.getElementById('eventDate').value,title=document.getElementById('eventTitle').value,time=document.getElementById('eventTime').value;if(!date||!title)return;let d=ensureDay(date);d.agenda.push({time,title,type:'event',location:document.getElementById('eventLocation').value,notes:document.getElementById('eventNotes').value,canceled:false});sortAgenda(d.agenda);state.selectedDate=date;let p=parseKey(date);state.year=p.y;state.month=p.m;save();setTab('calendar')}
function autoFillClient(){let name=document.getElementById('jobClient').value.trim();let c=state.clients?.[name];if(!c)return;if(!document.getElementById('jobPhone').value)document.getElementById('jobPhone').value=c.phone||'';if(!document.getElementById('jobAddress').value)document.getElementById('jobAddress').value=c.address||''}
function upsertClientFromJob(job){if(!state.clients)state.clients={};let n=job.client.trim();if(!n)return;if(!state.clients[n])state.clients[n]={name:n,phone:'',address:'',notes:''};if(job.phone)state.clients[n].phone=job.phone;if(job.address)state.clients[n].address=job.address;if(job.notes&&!state.clients[n].notes)state.clients[n].notes=job.notes}
function syncClientsFromJobs(){if(!state.clients)state.clients={};Object.keys(state.calendarData||{}).forEach(date=>{(state.calendarData[date].agenda||[]).forEach(a=>{if(a.type==='job'&&a.client)upsertClientFromJob(a)})});save()}
function openClient(n){state.selectedClient=n;state.tabs.clients='client';save();render()}
function saveClientEdit(){let old=state.selectedClient;let name=document.getElementById('clientNameEdit').value.trim();if(!name)return;if(!state.clients)state.clients={};if(name!==old){delete state.clients[old];renameClientInJobs(old,name)}state.clients[name]={name,phone:document.getElementById('clientPhoneEdit').value,address:document.getElementById('clientAddressEdit').value,notes:document.getElementById('clientNotesEdit').value};state.selectedClient=name;save();render()}
function renameClientInJobs(oldName,newName){Object.keys(state.calendarData||{}).forEach(date=>(state.calendarData[date].agenda||[]).forEach(a=>{if(a.client===oldName)a.client=newName}))}
function jobsForClient(n){let out=[];Object.keys(state.calendarData||{}).forEach(date=>(state.calendarData[date].agenda||[]).forEach(a=>{if(a.type==='job'&&a.client===n)out.push({...a,date})}));return out.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))}
function clientTotals(n){let jobs=jobsForClient(n),hours=0,charged=0,paid=0;jobs.forEach(j=>{if(!j.canceled){hours+=Number(j.hours||0);charged+=Number(j.owed||0);paid+=Number(j.received||0)}});return{hours,charged,paid,balance:Math.max(charged-paid,0)}}
function toggleCancel(idx){let d=ensureDay(state.selectedDate);d.agenda[idx].canceled=!d.agenda[idx].canceled;save();render()}
function updateTask(idx,key,value){ensureDay(state.selectedDate).tasks[idx][key]=value;save();renderCalendarOnlySoon()}
function deleteTask(idx){ensureDay(state.selectedDate).tasks.splice(idx,1);save();render()}
function addTask(){let text=document.getElementById('newTaskText').value.trim();if(!text)return;ensureDay(state.selectedDate).tasks.push({text,done:false});save();render()}
function updateNotes(value){ensureDay(state.selectedDate).notes=value;save()}
function calcJobPay(){let start=document.getElementById('jobStart')?.value||'',end=document.getElementById('jobEnd')?.value||'',hoursEl=document.getElementById('jobHours'),rateEl=document.getElementById('jobRate'),typeEl=document.getElementById('jobPayType'),owedEl=document.getElementById('jobOwed');if(hoursEl&&start&&end){let h=hoursBetween(start,end);if(h!==null)hoursEl.value=h.toFixed(h%1===0?0:2)}let hours=Number(hoursEl?.value||0),rate=Number(rateEl?.value||0),type=typeEl?.value||'hourly',total=type==='flat'?rate:hours*rate;if(owedEl)owedEl.value=total?total.toFixed(2):''}
function hoursBetween(start,end){let a=parseFlexibleTime(start),b=parseFlexibleTime(end);if(a===null||b===null)return null;let mins=b-a;if(mins<0)mins+=1440;return mins/60}
function parseFlexibleTime(t){t=String(t||'').trim().toLowerCase();let m=t.match(/^(\\d{1,2})(?::(\\d{2}))?\\s*([ap])?m?$/);if(!m)return null;let h=Number(m[1]),min=Number(m[2]||0),ap=m[3];if(ap==='p'&&h<12)h+=12;if(ap==='a'&&h===12)h=0;if(h>23||min>59)return null;return h*60+min}
function sortAgenda(arr){arr.sort((a,b)=>timeValue(a.time)-timeValue(b.time))}
function timeValue(t){t=String(t||'').toLowerCase().trim();let m=t.match(/(\\d{1,2})(?::(\\d{2}))?\\s*([ap])?/);if(!m)return 9999;let h=Number(m[1]),min=Number(m[2]||0),ap=m[3];if(ap==='p'&&h<12)h+=12;if(ap==='a'&&h===12)h=0;return h*60+min}
function formatTime(t){t=String(t||'').trim().toLowerCase();if(!t)return'';if(t.includes('a')||t.includes('p'))return t.replace(':00','');if(t.includes(':')){let [h,min]=t.split(':');h=Number(h);let ap=h>=12?'p':'a';h=h%12||12;return min==='00'?`${h}${ap}`:`${h}:${min}${ap}`}return t}
let softRenderTimer=null;function renderCalendarOnlySoon(){clearTimeout(softRenderTimer);softRenderTimer=setTimeout(()=>render(),650)}
function money(n){return '$'+Number(n||0).toFixed(2)}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function escapeAttr(s=''){return String(s).replace(/'/g,"\\\\'").replace(/"/g,'&quot;')}
function backup(){let b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});let u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='bird-planner-backup.json';a.click();URL.revokeObjectURL(u)}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
render();
